default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: "https://github.com/psf/black"
    rev: "24.2.0"
    hooks:
      - id: black
        stages: [commit]

  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v3.15.0"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  #  - repo: "https://github.com/kynan/nbstripout"
  #    rev: "0.5.0"
  #    hooks:
  #      - id: nbstripout
  #        stages: [commit]

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        stages: [commit]
        exclude: tests\/test_.+\.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.2.2"
    hooks:
      - id: ruff
        stages: [commit]

  #  - repo: https://github.com/PyCQA/doc8
  #    rev: "v1.1.1"
  #    hooks:
  #      - id: doc8
  #        stages: [commit]

  - repo: https://github.com/FHPythonUtils/LicenseCheck
    rev: "2024"
    hooks:
      - id: licensecheck
        stages: [commit]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        stages: [commit]
        additional_dependencies:
          - tomli
