default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: "https://github.com/commitizen-tools/commitizen"
    rev: "v2.18.0"
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: "https://github.com/kynan/nbstripout"
    rev: "0.5.0"
    hooks:
      - id: nbstripout
        stages: [pre-commit]

  - repo: "https://github.com/pycontribs/mirrors-prettier"
    rev: "v3.4.2"
    hooks:
      - id: prettier
        stages: [pre-commit]
        exclude: tests\/test_.+\.

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.0"
    hooks:
      - id: ruff
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: "v1.0.0"
    hooks:
      - id: sphinx-lint
        stages: [pre-commit]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        stages: [pre-commit]
        additional_dependencies:
          - tomli

  # Prevent committing inline conflict markers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
        stages: [pre-commit]
        args: [--assume-in-merge]
